batch_size: &batch_size 256
save_epochs: 10
reduce: sum

optimizer:
  optimizer: SGD
  base_lr: 0.1
  base_batch_size: 256
  batch_size: *batch_size
  momentum: 0.9
  weight_decay: 0.0001

scheduler:
  sched: multistep
  epochs: 120
  warmup_epochs: 0
  decay_milestones: [30, 60, 90]
  decay_rate: 0.1
  sched_on_update: False